version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: doctors

  doctors:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8091"